import { Sparkles, Crown } from "lucide-react";

export const plans = [
  {
    key: "starter",
    name: "Starter Plan",
    price: "₹299",
    description: "Download 10 high-quality food images.",
    features: [
      "10 image downloads",
      "Zomato & Swiggy approved photos",
      "High-quality images",
    ],
    button: "Get Starter Plan",
    link: "/payment/cart?plan=starter",
    highlight: false,
    duration: 30,
    amount: 299,
    discountedAmount: 299,
    discountPercentage: 0,
    taxPercentage: 18,
    downloads: 10,
    uploadAddonAmount: 499,
  },
  {
    key: "basic",
    name: "Basic Plan",
    price: "₹499",
    description: "Download 25 high-quality food images.",
    features: [
      "25 image downloads",
      "Zomato & Swiggy approved photos",
      "Access to trending photo packs",
      "High-quality images",
    ],
    button: "Get Basic Plan",
    link: "/payment/cart?plan=basic",
    highlight: false,
    duration: 30,
    amount: 499,
    discountedAmount: 499,
    discountPercentage: 0,
    taxPercentage: 18,
    downloads: 25,
    uploadAddonAmount: 799,
  },
  {
    key: "pro",
    name: "Pro Plan",
    price: "₹999",
    description: "Download 80 high-quality food images.",
    features: [
      "80 image downloads",
      "Access to entire photo library",
      "Zomato & Swiggy approved photos",
      "High-quality food images",
      "Priority photo requests",
    ],
    button: "Go Pro",
    link: "/payment/cart?plan=pro",
    highlight: false,
    duration: 30,
    amount: 999,
    discountedAmount: 999,
    discountPercentage: 0,
    taxPercentage: 18,
    downloads: 80,
    uploadAddonAmount: 1199,
  },
  {
    key: "premium",
    name: "Premium Plan",
    price: "₹1,999",
    description: "Download unlimited high-quality food images.",
    features: [
      "Unlimited image downloads",
      "Full access to photo library",
      "Zomato & Swiggy approved photos",
      "Priority photo request handling",
      "Exclusive new photo collections",
      "High-quality images",
    ],
    button: "Go Premium",
    link: "/payment/cart?plan=premium",
    highlight: true,
    duration: 30,
    amount: 1999,
    discountedAmount: 1999,
    discountPercentage: 0,
    taxPercentage: 18,
    downloads: "unlimited",
    uploadAddonAmount: 1499,
  },
];

export const services = [
  {
    key: "dfy-photo-upload",
    name: "Done-For-You Photo & Menu Upload",
    price: "Starting from ₹1,000",
    tagline: "Our team formats & uploads up to 150 food photos on your behalf",
    description:
      "Our team uploads, formats, and tags your chosen high-resolution food photos directly to your restaurant's Zomato & Swiggy menus on your behalf.",
    tiers: [
      {
        key: "tier-40",
        label: "Up to 40 Items",
        items: 40,
        price: "₹1,000",
        amount: 1000,
        badge: "Starter",
      },
      {
        key: "tier-80",
        label: "Up to 80 Items",
        items: 80,
        price: "₹1,500",
        amount: 1500,
        badge: "Popular",
        isPopular: true,
      },
      {
        key: "tier-150",
        label: "Up to 150 Items",
        items: 150,
        price: "₹2,500",
        amount: 2500,
        badge: "Best Value",
      },
    ],
    features: [
      "Item-to-photo matching for Zomato & Swiggy",
      "Resolution & aspect ratio optimization",
      "Direct upload via merchant portal or manager access",
      "100% platform approval guarantee",
      "Turnaround completed within 24–48 hours",
    ],
    badge: "⚡ Most Popular Add-on",
    button: "Order Photo Upload",
    highlight: true,
    amount: 1000,
    image: "/assets/banners/upload-service.webp",
  },
  {
    key: "zomato-swiggy-setup",
    name: "Complete Zomato + Swiggy Setup",
    price: "₹3,499",
    tagline: "End-to-end merchant onboarding & menu setup up to 50 items",
    description:
      "End-to-end onboarding: account creation, menu setup up to 50 items, photo optimization, and full platform setup for both Zomato & Swiggy.",
    features: [
      "Create/claim Zomato & Swiggy merchant accounts",
      "Full menu setup & digitization up to 50 items",
      "Image selection & platform-compliant resizing",
      "Item descriptions, pricing & category mapping",
      "1 month menu update & rate change assistance",
      "Ads & promotions launch guidance",
    ],
    badge: "🚀 Full Setup",
    button: "Order Full Setup",
    highlight: false,
    amount: 3499,
    image: "/assets/banners/store-setup.jpg",
  },
  {
    key: "food-license",
    name: "FSSAI Food License Registration",
    price: "Starting from ₹699",
    tagline: "1-Year (₹699 in 24h) or 5-Year (₹2,499 in 7–15 days)",
    description:
      "Assistance with food license application paperwork and submission guidance so you get compliant quickly.",
    features: [
      "1-Year (₹699 in 24h) or 5-Year (₹2,499 in 7–15 days)",
      "Government Application Fees Included",
      "Dedicated Account Manager",
      "Free Consultancy on Compliance",
      "Updates on Application Status",
      "Secure & Encrypted Processing",
    ],
    badge: "📋 Fast Compliance",
    button: "Get License Help",
    highlight: false,
    amount: 699,
    image: "/assets/banners/food-license.png",
  },
];

export const fssaiPlans = [
  {
    key: "food-license-1yr",
    durationKey: "1yr",
    name: "1-Year FSSAI Food License",
    durationLabel: "1-Year Validity",
    price: "₹699",
    amount: 699,
    discountedAmount: 699,
    turnaround: "Ready in 24 Hours",
    turnaroundDays: "24h fast-track",
    originalPrice: "₹2,999",
    savings: "SAVE ₹2,300",
    description: "Fast-track 1-Year FSSAI basic registration for cloud kitchens, restaurants & food outlets.",
    features: [
      "1-Year Official FSSAI Registration",
      "Fast-Track 24h Application Submission",
      "Government Application Fees Included",
      "Dedicated Compliance Account Manager",
      "Free Consultation & Verification",
      "WhatsApp Status & Certificate Delivery",
    ],
    button: "Apply for 1-Year (₹699)",
    highlight: false,
    badge: "⚡ Fast 24h Turnaround",
  },
  {
    key: "food-license-5yr",
    durationKey: "5yr",
    name: "5-Year FSSAI Food License",
    durationLabel: "5-Year Validity",
    price: "₹2,499",
    amount: 2499,
    discountedAmount: 2499,
    turnaround: "7–15 Days",
    turnaroundDays: "7–15 days complete processing",
    originalPrice: "₹7,999",
    savings: "SAVE ₹5,500 (Best Value)",
    description: "5-Year Long-Term FSSAI Registration. Zero yearly renewal hassle for 5 straight years.",
    features: [
      "5-Year Official FSSAI Registration",
      "No Renewal Hassle for 5 Full Years",
      "Government Application Fees Included",
      "Dedicated Compliance Account Manager",
      "Free Consultation & Verification",
      "WhatsApp Status & Certificate Delivery",
    ],
    button: "Apply for 5-Year (₹2,499)",
    highlight: true,
    badge: "⭐ Best Value (5 Years)",
  },
];

export const PLAN_TIER_CONFIGS = {
  starter: {
    icon: Sparkles,
    perImage: "₹29.90 / image",
    tagline: "Great for expanding multi-cuisine restaurants",
    badge: null,
    badgeClass: "",
    accentColor: "border-border/70 hover:border-primary/40",
    buttonClass:
      "border border-primary text-primary bg-primary/5 hover:bg-primary hover:text-primary-foreground font-semibold",
    isFeatured: false,
  },
  basic: {
    icon: Sparkles,
    perImage: "₹19.96 / image",
    tagline: "Great for expanding multi-cuisine restaurants",
    badge: null,
    badgeClass: "",
    accentColor: "border-border/70 hover:border-primary/40",
    buttonClass:
      "border border-primary text-primary bg-primary/5 hover:bg-primary hover:text-primary-foreground font-semibold",
    isFeatured: false,
  },
  pro: {
    icon: Sparkles,
    perImage: "₹12.49 / image",
    tagline: "Best value for growing restaurants & food chains",
    badge: null,
    badgeClass: "",
    accentColor: "border-border/70 hover:border-primary/40",
    buttonClass:
      "border border-primary text-primary bg-primary/5 hover:bg-primary hover:text-primary-foreground font-semibold",
    isFeatured: false,
  },
  premium: {
    icon: Crown,
    perImage: "Unlimited Downloads",
    tagline: "High volume access for agencies & restaurant groups",
    badge: "⭐ UNLIMITED ACCESS",
    badgeClass:
      "bg-primary text-primary-foreground font-semibold shadow-md shadow-primary/30",
    accentColor:
      "border-primary shadow-xl shadow-primary/10 ring-2 ring-primary/40 bg-gradient-to-b from-primary/5 via-card to-card",
    buttonClass:
      "bg-primary hover:bg-primary/90 text-primary-foreground shadow-lg shadow-primary/25 font-semibold",
    isFeatured: true,
  },
};

export const DEFAULT_PLAN_CONFIG = {
  icon: Sparkles,
  perImage: null,
  tagline: "High quality food photography",
  badge: null,
  badgeClass: "",
  accentColor: "border-border hover:border-primary/30",
  buttonClass:
    "border border-primary text-primary bg-primary/5 hover:bg-primary hover:text-primary-foreground font-semibold",
  isFeatured: false,
};

export const photoUploadPlans = [
  {
    key: "dfy-upload-40",
    name: "Starter Upload",
    price: "₹1,000",
    amount: 1000,
    discountedAmount: 1000,
    items: 40,
    perItem: "₹25 / dish",
    tagline: "Upload up to 40 food dishes",
    description: "Our experts format, optimize, and upload up to 40 food dish photos to your Zomato & Swiggy menus.",
    features: [
      "Upload & tag up to 40 food dishes",
      "Zomato & Swiggy platform resizing",
      "Item-to-photo matching & categorization",
      "100% platform approval guarantee",
      "Turnaround in 24–48 hours",
    ],
    button: "Order 40 Dishes Upload",
    highlight: false,
    badge: null,
  },
  {
    key: "dfy-upload-80",
    name: "Growth Upload",
    price: "₹1,500",
    amount: 1500,
    discountedAmount: 1500,
    items: 80,
    perItem: "₹18.75 / dish",
    tagline: "Upload up to 80 food dishes",
    description: "Best for busy restaurants & cafes with extensive multi-category menus.",
    features: [
      "Upload & tag up to 80 food dishes",
      "Zomato & Swiggy platform resizing",
      "Item-to-photo matching & categorization",
      "100% platform approval guarantee",
      "Priority Turnaround (24 hours)",
      "1 free revision after upload",
    ],
    button: "Order 80 Dishes Upload",
    highlight: true,
    badge: "⚡ Most Popular",
  },
  {
    key: "dfy-upload-150",
    name: "Scale Upload",
    price: "₹2,500",
    amount: 2500,
    discountedAmount: 2500,
    items: 150,
    perItem: "₹16.66 / dish",
    tagline: "Upload up to 150 food dishes",
    description: "Ideal for large menus, cloud kitchen chains, and multi-outlet food brands.",
    features: [
      "Upload & tag up to 150 food dishes",
      "Multi-outlet or large menu support",
      "Zomato & Swiggy platform resizing",
      "Item-to-photo matching & categorization",
      "100% platform approval guarantee",
      "Dedicated account specialist",
      "Unlimited revisions for first week",
    ],
    button: "Order 150 Dishes Upload",
    highlight: false,
    badge: "⭐ Best Value",
  },
];

export const zomatoSwiggyPlans = [
  {
    key: "zomato-swiggy-setup",
    name: "Complete Zomato + Swiggy Setup",
    price: "₹3,499",
    amount: 3499,
    discountedAmount: 3499,
    items: 50,
    perItem: "Zomato & Swiggy Included",
    tagline: "End-to-end merchant onboarding & menu setup up to 50 items",
    description: "Complete merchant registration, full digital menu setup & photo uploads up to 50 items on both Zomato & Swiggy.",
    features: [
      "Zomato & Swiggy merchant account creation & onboarding",
      "Full digital menu digitization & structuring (up to 50 items)",
      "Photo selection, compliant resizing & upload (up to 50 items)",
      "Category, bestsellers & cuisine mapping",
      "1 month post-launch menu update & rate change assistance",
      "Direct guidance for initial ads & discounts setup",
      "Official platform registration fee to be paid directly to Zomato/Swiggy by customer",
    ],
    button: "Order Full Setup (₹3,499)",
    highlight: true,
    badge: "🚀 Full Store Setup",
  },
];
